<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="<?= PATH ?>/public/css/estilo.css">
     <!-- importa o css "<?= PATH ?>public/css/estilos.css" -->
    <title> Projeto Slim Micro framework 3 </title>
  </head>
  <body>
    <header id="topo-um">
        <div class="container">
          <h1 class="logo-site"> Logo do site </h1>

          <nav id="menu">
            <ul>
              <li> <a href="<?= PATH ?>/"        alt="Home">    Home    </a> </li>
              <li> <a href="<?= PATH ?>/contato" alt="Contato"> Contato </a> </li>
              <li> <a href="<?= PATH ?>/sobre"   alt="sobre">   Sobre    </a> </li>
            </ul>
          </nav>
        </div>
    </header>

    <section>
      <div class="container">
