<div class="container">

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2> Novo Post </h2>

      <div class="panel panel-default">
          <div class="panel-heading">
              Formulário de postagens
          </div>
          <div class="panel-body">
            <!-- colocar Formulário -->
            <form>
                <div class="form-group">
                  <label for="titulo"> Título </label>
                  <input type="text" class="form-control" id="titulo" placeholder="título">
                </div>

                <div class="form-group">
                  <label for="descricao"> Descrição </label>
                  <textarea class="form-control" id="descricao"  rows="3" placeholder="descrição"/></textarea>
                </div>

                <button type="submit" class="btn btn-default"> Cadastrar </button>
            </form>
          </div>

      </div>
    </div>

  </div>
</div>
