<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2> Posts </h2>
            <a href="<?= PATH ?>/admin/posts/add" class="btn btn-primary"> Novo Post</a>
            </br>
            </br>
            <div class="panel panel-default">
                <div class="panel-heading">
                    Lista de postagens
                </div>

                <div class="panel-body">
                    <table class="table">
                        <thead>
                          <tr>
                            <th>#</th> <th>Título</th> <th>Ações</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>1</td>
                            <td> Título de Postagem qualquer </td>
                            <td>
                                <a class="btn btn-info"    href="#"> Visualizar </a>
                                <a class="btn btn-warning" href="#"> Editar     </a>
                                <a class="btn btn-danger"  href="#"> Excluir    </a>
                            </td>
                          </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
