<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2> Posts </h2>
            <!-- <h3> Vem vindo aos posts! :-) </h3> -->
            <div class="panel default-panel">
                <div class="panel-heading">
                    Lista de postagens
                </div>

                <div class="panel-body">
                  Postagens
                </div>
            </div>
        </div>
    </div>
</div>
