<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
  <head>
    <meta charset="utf-8">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <style>
        body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #eee;
        }

        .form-signin {
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
        }
        .form-signin .form-signin-heading,
        .form-signin .checkbox {
        margin-bottom: 10px;
        }
        .form-signin .checkbox {
        font-weight: normal;
        }
        .form-signin .form-control {
        position: relative;
        height: auto;
        -webkit-box-sizing: border-box;
           -moz-box-sizing: border-box;
                box-sizing: border-box;
        padding: 10px;
        font-size: 16px;
        }
        .form-signin .form-control:focus {
        z-index: 2;
        }
        .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
        }
        .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
        }
    </style>

    <title> Faça aqui o seu login </title>
  </head>
  <body>
    <div class="container" Action="<?= PATH ?>/admin/login/logar" method="POST">
      
      <?php if ( isset($erro) ) { ?>
          <div class="alert alert-danger">
            <?= $erro?>
          </div>
      <?php } ?>

      <form class="form-signin" action="<?= PATH ?>/admin/login" method="POST">
        <h2 class="form-signin-heading"> Faça seu login </h2>
        <label for="inputEmail" class="sr-only"> Endereço de e-mail </label>
        <input type="email" name="email" id="inputEmail" class="form-control" placeholder="E-mail" required autofocus>

        <label for="inputPassword" class="sr-only"> Senha </label>
        <input type="password" name="senha" id="inputPassword" class="form-control" placeholder="Senha" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Lembre-me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit"> Entrar </button>
      </form>
    </div>
  </body>
</html>
